IvanKolevBossSystem/Models/Transaction.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace IvanKolevBossSystem.Models
{
    public class Transaction
    {
        public Transaction()
        {
            this.Date = DateTime.Now;   
        }
        [Key]
        public int Id { get; set; }

        [Required]
        public ApplicationUser User { get; set; }

        public int SockAmount { get; set; }

        public decimal CurrentSockPrice { get; set; }

        [Required]
        public decimal AmountOfMoney { get; set; }

        [Required]
        public string TypeOfTransaction { get; set; }

        [Required]
        public string CurrentAccBalance { get; set; }

        public DateTime Date { get; set; }
    }
}

IvanKolevBossSystem/Controllers/MarketController.cs
using IvanKolevBossSystem.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;


namespace IvanKolevBossSystem.Controllers
{
    public class MarketController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private Transaction transaction = new Transaction();


        public Sock getCurrentSockInfo()
        {
            Sock currentSockInfo = db.Socks.OrderByDescending(s => s.Id).FirstOrDefault();
            return currentSockInfo;
        }
        // GET: Market/Marketplace/Id
        public ActionResult Marketplace(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ApplicationUser applicationUser = db.Users.Find(id);
            if (applicationUser == null)
            {
                return HttpNotFound();
            }


            var MarketplaceUserInfo = new MarketplaceUserInfo(applicationUser, getCurrentSockInfo());

            return View(MarketplaceUserInfo);
        }

        // POST: Market/Marketplace/Id
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Marketplace(string id, string money,string typeOfTransaction, string numberOfSocks = "")
        {
            var types = new string[] { "S", "D", "B" }; //allowed types

            ApplicationUser applicationUser = db.Users.Find(id);

            if (id == null || Array.IndexOf(types, typeOfTransaction) < 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var MarketplaceUserInfo = new MarketplaceUserInfo(applicationUser, getCurrentSockInfo());

            if (typeOfTransaction == "D")
            {
                //deposit
               
                decimal moneyToAdd;
                if (!decimal.TryParse(money, out moneyToAdd))
                {
                    ModelState.AddModelError("money", "Deposit amount must be a number!");
                    return View(MarketplaceUserInfo);
                }
                applicationUser.AvailableBalance += moneyToAdd;

                //transaction fill data
                transaction.AmountOfMoney = moneyToAdd;
                transaction.TypeOfTransaction = typeOfTransaction;
                transaction.User = applicationUser;
                transaction.CurrentAccBalance = applicationUser.AvailableBalance.ToString();


                //Success message : You have successfully deposited {moneyToAdd} to your account!

            }
            else if (typeOfTransaction == "B")
            {
                //buy                

                int NumberOfSocks;
                if (!int.TryParse(numberOfSocks, out NumberOfSocks))
                {
                    ModelState.AddModelError("numberOfSocks", "Number of socks must be a number!");
                    return View(MarketplaceUserInfo);
                }
                Sock sockInfo = getCurrentSockInfo();
                decimal moneyToWithdraw = NumberOfSocks * sockInfo.Price;
                if(moneyToWithdraw > applicationUser.AvailableBalance)
                {
                    ModelState.AddModelError("numberOfSocks", $"You don't have enough money to buy {NumberOfSocks} socks!");
                    return View(MarketplaceUserInfo);
                }
                applicationUser.AvailableBalance -= moneyToWithdraw;
                applicationUser.SocksCount += NumberOfSocks;
                //transaction fill data
                transaction.AmountOfMoney = moneyToWithdraw;
                transaction.TypeOfTransaction = typeOfTransaction;
                transaction.User = applicationUser;
                transaction.CurrentAccBalance = applicationUser.AvailableBalance.ToString();
                transaction.CurrentSockPrice = sockInfo.Price;
                transaction.SockAmount = NumberOfSocks;

                //Success message : You have successfully bought {NumberOfSocks} socks!

            }
            else 
            {
                //sell

                int NumberOfSocks;
                if (!int.TryParse(numberOfSocks, out NumberOfSocks))
                {
                    ModelState.AddModelError("numberOfSocks", "Number of socks must be a number!");
                    return View(MarketplaceUserInfo);
                }
                Sock sockInfo = getCurrentSockInfo();
                decimal moneyToAdd = NumberOfSocks * sockInfo.Price;
                if (NumberOfSocks > applicationUser.SocksCount)
                {
                    ModelState.AddModelError("numberOfSocks", $"You don't have enough socks to sell - {applicationUser.SocksCount} socks left!");
                    return View(MarketplaceUserInfo);
                }
                applicationUser.AvailableBalance += moneyToAdd;
                applicationUser.SocksCount -= NumberOfSocks;

                //transaction fill data
                transaction.AmountOfMoney = moneyToAdd;
                transaction.TypeOfTransaction = typeOfTransaction;
                transaction.User = applicationUser;
                transaction.CurrentAccBalance = applicationUser.AvailableBalance.ToString();
                transaction.CurrentSockPrice = sockInfo.Price;
                transaction.SockAmount = NumberOfSocks;

                //Success message : You have successfully sold {NumberOfSocks} socks!
            }

            if (ModelState.IsValid)
            {
                db.Transactions.Add(transaction);
                db.Entry(applicationUser).State = EntityState.Modified;
                db.SaveChanges();
            }

            return View(MarketplaceUserInfo);
        }

        // GET: Market/Transactions
        public ActionResult Transactions()
        {
            var transactions = db.Transactions.Where(t => t.TypeOfTransaction != "D").Include(t => t.User).OrderByDescending(t => t.Date).ToList();
            return View(transactions);
        }


        // GET: Market/Transactions/Id
        public ActionResult UserTransactions(string id)
        {
            ApplicationUser applicationUser = db.Users.Find(id);

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var userTransactions = db.Transactions.Where(t => t.User.Id == applicationUser.Id).Include(t => t.User).OrderByDescending(t => t.Date).ToList();
            return View(userTransactions);
        }

    }
}

IvanKolevBossSystem/Views/Market/Marketplace.cshtml
@Styles.Render("~/Content/css")

@model IvanKolevBossSystem.Models.MarketplaceUserInfo
@{
    ViewBag.Title = "Marketplace";
}
<h2>Marketplace</h2>

<script src="@Url.Content("~/Scripts/custom.js")"></script>



<h4>User: @Model.User.FullName</h4>
<hr />
<div class="form-group">
    <div class="row">
        <div class="col-md-3">Available balance: </div>
        <div class="col-md-1">@Model.User.AvailableBalance</div>
    </div>
    <div class="row">
        <div class="col-md-3">Your Socks: </div>
        <div class="col-md-1">@Model.User.SocksCount</div>
    </div>
    <div class="row">
        <div class="col-md-3">Current Sock price: </div>
        <div class="col-md-1">@Model.Sock.Price</div>
    </div>
</div>

@using (Html.BeginForm("Marketplace", "Market"))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @*@Html.HiddenFor(model => model.Id)*@
        <input type="hidden" id="typeOfTransaction" name="typeOfTransaction" value="D">
        <input type="hidden" id="id" name="id" value="@Model.User.Id">
        <input type="text" id="money" name="money" />
        <p  id="deposit" class="btn btn-default">Deposit</p>
        @*<input type="submit" value="Add money to your account balance" class="btn btn-default" />*@
    </div>
}
@using (Html.BeginForm("Marketplace", "Market"))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @*@Html.HiddenFor(model => model.Id)*@
        <input type="hidden" name="typeOfTransaction" value="B">
        <input type="hidden" name="id" value="@Model.User.Id">
        <input type="text" name="numberOfSocks" />
        @if (Model.User.AvailableBalance < Model.Sock.Price)
        {
            <input type="submit" value="Buy socks" class="btn btn-default" disabled } />
        }
        else
        {
            <input type="submit" value="Buy socks" class="btn btn-default" } />
        }
    </div>
}
@using (Html.BeginForm("Marketplace", "Market"))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @*@Html.HiddenFor(model => model.Id)*@
        <input type="hidden" name="typeOfTransaction" value="S">
        <input type="hidden" name="id" value="@Model.User.Id">
        <input type="text" name="numberOfSocks" />
        @if (Model.User.SocksCount <= 0)
        {
            <input type="submit" value="Sell socks" class="btn btn-default" disabled } />
        }
        else
        {
            <input type="submit" value="Sell socks" class="btn btn-default" } />
        }


    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

IvanKolevBossSystem/Views/Market/Transactions.cshtml
@Styles.Render("~/Content/css")

@model  IEnumerable<IvanKolevBossSystem.Models.Transaction>
@{
    ViewBag.Title = "Transactions";
}

<h2>All transactions</h2>
    <table>
        <tr>
            <th>USERNAME</th>
            <th>NUMBER OF SOCKS</th>
            <th>SOCK PRICE</th>
            <th>MONEY AMOUNT</th>
            <th>TRANSACTION TYPE</th>
            <th>DATE</th>
        </tr>

        @foreach (var transaction in Model)
        {
            <tr class="@transaction.TypeOfTransaction">
                <td>
                    @if (transaction.User.FullName != null)
                    {
                        @transaction.User.FullName@:(@transaction.User.Email)
                    }
                    else
                    {
                        @:N/A(@transaction.User.Email)
                    }
                </td>
                <td>@transaction.SockAmount</td>
                <td>@transaction.CurrentSockPrice</td>
                @if (transaction.TypeOfTransaction == "B")
                {
                    <td>- @transaction.AmountOfMoney</td>
                }
                else
                {
                    <td>+ @transaction.AmountOfMoney</td>
                }
                @if (transaction.TypeOfTransaction == "S")
                {
                    <td>SELL</td>
                }
                else
                {
                    <td>BUY</td>
                }
                <td>@(transaction.Date.ToString("MM/dd/yyyy HH:mm"))</td>
            </tr>
        }
    </table>

IvanKolevBossSystem/Views/Market/UserTransactions.cshtml
@Styles.Render("~/Content/css")

@model  IEnumerable<IvanKolevBossSystem.Models.Transaction>
@{
    ViewBag.Title = "Your transactions";
}

<h2>Your transactions</h2>
    <table>
        <tr>
            <th>NUMBER OF SOCKS</th>
            <th>SOCK PRICE</th>
            <th>MONEY AMOUNT</th>
            <th>TRANSACTION TYPE</th>
            <th>ACCOUNT BALANCE</th>
            <th>DATE</th>
        </tr>

        @foreach (var transaction in Model)
        {
            <tr class="@transaction.TypeOfTransaction">
                @if (transaction.TypeOfTransaction != "D")
                {
                    if (transaction.TypeOfTransaction == "S")
                    {
                        <td>- @transaction.SockAmount</td>

                    }
                    else 
                    {
                        <td>+ @transaction.SockAmount</td>

                    }
                    <td>@transaction.CurrentSockPrice</td>
                }
                else
                {
                    <td>-</td>
                    <td>-</td>
                }
                @if (transaction.TypeOfTransaction == "B")
                {
                    <td>- @transaction.AmountOfMoney</td>
                    <td>BUY</td>
                }
                else if (transaction.TypeOfTransaction == "S")
                {
                    <td>+ @transaction.AmountOfMoney</td>
                    <td>SELL</td>
                }
                else
                {
                    <td>+ @transaction.AmountOfMoney</td>
                    <td>DEPOSIT</td>
                }
                
                
                <td>@transaction.CurrentAccBalance</td>
                <td>@(transaction.Date.ToString("MM/dd/yyyy HH:mm"))</td>
            </tr>
        }
    </table>